require('plugin_config.gruvbox')
require('plugin_config.lualine')
--require('plugin_config.nvimtree')
require('plugin_config.treesitter')
require('plugin_config.telescope')
--require('plugin_config.lsp_config')
require('plugin_config.completions')
